export const BLOCK_NAMESPACE = 'smfcs';

export const BLOCKS = {
    FLASHCARD_SET: `${BLOCK_NAMESPACE}/flashcard-set`,
    FLASHCARD: `${BLOCK_NAMESPACE}/flashcard`,
    FLASHCARD_FRONT: `${BLOCK_NAMESPACE}/flashcard-front`,
    FLASHCARD_BACK: `${BLOCK_NAMESPACE}/flashcard-back`
};

export const FLASHCARD_SET_ALLOWED_BLOCKS = [BLOCKS.FLASHCARD];
export const FLASHCARD_SET_DEFAULT_TEMPLATE = [[BLOCKS.FLASHCARD]]; 

export const FLASHCARD_ALLOWED_BLOCKS = [BLOCKS.FLASHCARD_FRONT, BLOCKS.FLASHCARD_BACK];
export const FLASHCARD_TEMPLATE = [
	[BLOCKS.FLASHCARD_FRONT],
	[BLOCKS.FLASHCARD_BACK]
];
